import type { Metadata } from "next";
import { Geist, Instrument_Serif, Instrument_Sans } from "next/font/google";
import "./globals.css";
import CookieConsent from "@/components/cookie";
import MachineToggle from "@/components/machine-toggle";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  weight: "400",
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSerif.variable} ${instrumentSans.variable} h-full antialiased`}
    >
      <body className="font-sans">
        {children}
        <CookieConsent />
        <MachineToggle />
      </body>
    </html>
  );
}
